name: jarvis_app
description: Offline Jarvis Assistant
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
