name: jarvis_app
description: Offline Jarvis Assistant
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.0
  speech_to_text: ^6.6.0   # temp (later Whisper replace)
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
