name: Dynamic APK Builder Pro

on:
  workflow_dispatch:
    inputs:
      app_folder:
        description: 'నీ యాప్ ఉన్న ఫోల్డర్ పేరు (Ex: safecash_app)'
        required: true
        default: '.' # డైరెక్ట్ గా బయటే ఉంటే డాట్ (.) వాడతాం

jobs:
  build:
    name: Build & Upload Dynamic APK
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # ఇక్కడే అసలు మ్యాజిక్ జరుగుతుంది. నువ్వు ఇచ్చిన ఫోల్డర్ లోకి వెళ్లి బిల్డ్ చేస్తుంది.
      - name: 🛠️ Build Release APK
        run: |
          cd ${{ github.event.inputs.app_folder }}
          flutter pub get
          flutter build apk --release

      # ఏ యాప్ ని బిల్డ్ చేసామో ఆ పేరుతోనే APK సేవ్ అవుతుంది
      - name: 🚀 Upload Artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.app_folder }}-APK
          path: ${{ github.event.inputs.app_folder }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
